/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadernoRouteImport } from './routes/caderno'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as TalhoesRouteImport } from './routes/talhoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadernoRoute = CadernoRouteImport.update({
  id: '/caderno',
  path: '/caderno',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const TalhoesRoute = TalhoesRouteImport.update({
  id: '/talhoes',
  path: '/talhoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico': typeof HistoricoRoute
  '/talhoes': typeof TalhoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico': typeof HistoricoRoute
  '/talhoes': typeof TalhoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caderno': typeof CadernoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/historico': typeof HistoricoRoute
  '/talhoes': typeof TalhoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caderno' | '/diagnostico' | '/historico' | '/talhoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caderno' | '/diagnostico' | '/historico' | '/talhoes'
  id: '__root__' | '/' | '/caderno' | '/diagnostico' | '/historico' | '/talhoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadernoRoute: typeof CadernoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  HistoricoRoute: typeof HistoricoRoute
  TalhoesRoute: typeof TalhoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caderno': {
      id: '/caderno'
      path: '/caderno'
      fullPath: '/caderno'
      preLoaderRoute: typeof CadernoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talhoes': {
      id: '/talhoes'
      path: '/talhoes'
      fullPath: '/talhoes'
      preLoaderRoute: typeof TalhoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadernoRoute: CadernoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  HistoricoRoute: HistoricoRoute,
  TalhoesRoute: TalhoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
